### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by andreasbalevik** [markusranda/real-ni-hao-legends#2]
Instructions unclear, missing README.md

![](https://media.tenor.com/eRjjRricmzMAAAAM/krule-john-c-reilly.gif)

**Comment by markusranda** [comment]
Good evening Andreas

I'm sorry to hear that you were in need of a file named README.MD, and couldn't find one. This repository is actually extraordinary elitist and expect all it's visitors to understand everything we do at the absolute first glance.  

Best regards
Ni Hao Industries

**Comment by andreasbalevik** [comment]
Hello Mr. Randa

I recently reached out with the hope of finding crucial information in the README.MD file for your repository, a basic yet essential tool for navigating and understanding projects of all complexities. Unfortunately, you closed the issue without a solution.

To suggest that every visitor should instantly comprehend the intricacies of your work without the slightest guidance is not only unrealistic but also counterproductive.

Please reconsider your approach. 

Your project, no doubt, holds significant value and potential. It would be a shame for its reach and impact to be limited by an unwelcoming attitude. 

Best Regards
Andreas

**Comment by markusranda** [comment]
Dear Andreas,

Your message, like a lightning bolt on a calm day, certainly jolted my senses. Allow me to commend your flair for dramatic expression.

Ah, the humble README.MD file, a beacon of hope in the vast sea of project documentation. I appreciate your assertion of its importance, as if I were blissfully unaware of its existence. Your concern for lost souls wandering in the digital wilderness is duly noted.

However, your expectation that I hold the keys to enlightenment for every passerby is quite flattering, if not slightly delusional. While I strive for clarity, I can't promise to handhold every lost traveler who stumbles upon my repository. After all, a bit of adventure in the quest for knowledge never hurt anyone, right?

As for the closure of your issue, my dear Andreas, rest assured it wasn't a decision made with callous disregard. Sometimes, one must close the door to open a window, or some such metaphor. But fear not, your plea for reconsideration has stirred the dark depths of my soul, and I shall contemplate it under the moonlight.

Best regards
Ni Hao Industries

**Comment by andreasbalevik** [comment]
Mr. Randa, 

The core issue at hand seems to have been sidestepped rather than addressed, marking a notable lapse in both attention and action on your part. 

The closure of the issue without proper resolution not only underscores a failure to engage with the problem but also a certain level of ignorance towards the implications of such an act.

After careful consideration, I have decided to cease using your services and, henceforth, discontinue any further communication. This decision comes after recognizing a fundamental misalignment in expectations and outcomes. As such, I will also renounce any acknowledgment of your existence in my professional endeavors.

Let me leave you with this thought: "Even the mightiest gorilla, reigning supreme atop the food chain, must still descend from the mountain to quench its thirst." 

Not best regards
Andreas

**Comment by 0us** [comment]
Dear @andreasbalevik,

At Ni Hao Industries, we marvel at your quest for the README.m. Alas, our digital labyrinth was designed for the brave. It seems our paths diverge here, with you seeking clearer realms.

Mister, I do not know you and you do not know me - but rest assured, trough our shared passion for code, we are one and the same. Still, that does not make your request any less incorrect. 

As you swing away, remember: gorillas find bananas every day without a map. Godspeed on your trek to lands abundant with guidance.

Toodeloo,

Ni Hao Industries
